###################################################################################################

- name: kill | container

  when: dockable_container is defined
    and dockable_container is not none
    and dockable_container | length > 0

  include: kill.container.yml

###################################################################################################

- name: run | container

  command: '{{ dockable_base_command }} run -dp {{ dockable_expose_port }} {% if dockable_container is defined and dockable_container is not none and dockable_container | length > 0 %}--name {{ dockable_container }}{% endif %} {{ dockable_image_signature }}'

  register: run

###################################################################################################

- name: discover | port

  shell: "{{ dockable_base_command }} port {{ run.stdout }} {{ dockable_expose_port }} | awk -F':' '{print $2}'"

  register: port

  changed_when: false

###################################################################################################

- name: wait | up

  local_action: wait_for host={{ dockable_ssh_host }}
                         port={{ port.stdout }}
                        state=started

###################################################################################################

- name: add | host

  add_host:    name={{ dockable_container | default(run.stdout | truncate(12, true, '')) }}
   ansible_ssh_user={{ dockable_ssh_user                                                 }}
   ansible_ssh_host={{ dockable_ssh_host                                                 }}
   ansible_ssh_port={{ port.stdout                                                       }}
             groups={{ dockable_group                                                    }}

###################################################################################################
