###################################################################################################

- with_items: "{{ groups['containers'] }}"
  debug: var=item

- debug: var=hostvars

- with_items: "{{ groups['containers'] }}"
  shell: '{{ dockable_base_command }} stop {{ item }}'

- with_items: "{{ groups['containers'] }}"
  shell: '{{ dockable_base_command }} commit {{ item }}'
  register: commit

- debug: var=commit

- with_items: "{{ commit.results }}"
  shell: '{{ dockable_base_command }} tag --force {{ item.stdout }} {{ dockable_commit_signature }}'

###################################################################################################
