###################################################################################################

- shell: '{{ dockable_base_command }} stop {{ dockable_container }}'

- shell: '{{ dockable_base_command }} commit {{ dockable_container }}'
  register: commit

- shell: '{{ dockable_base_command }} tag --force {{ commit.stdout }} {{ dockable_commit_signature }}'

###################################################################################################
