###################################################################################################

- name: default

  when: dockable_target is none
     or dockable_target | length == 0

  set_fact:
    dockable_target: '{{ dockable_target_default }}'

###################################################################################################

- name: tcp

  when: "dockable_target | truncate({{ dockable_target_tcp | length }}, true, '') == '{{ dockable_target_tcp }}'"

  include: tcp.yml

###################################################################################################

- name: unix

  when: "dockable_target | truncate({{ dockable_target_unix | length }}, true, '') == '{{ dockable_target_unix }}'"

  include: unix.yml

###################################################################################################

### docker version --format '{{.Server.Version}}'

- name: verify

  command: '{{ dockable_base_command }} version'

  register: verify

  changed_when: false
  failed_when : verify.rc != 0 or 'server' not in verify.stdout | lower

###################################################################################################
