###################################################################################################

- name: default

  when: dockable_target is none
     or dockable_target | length == 0

  set_fact:
    dockable_target: '{{ dockable_target_default }}'

  tags:
    - dockable
    - target

###################################################################################################

- name: tcp

  when: "dockable_target | truncate({{ dockable_target_tcp | length }}, true, '') == '{{ dockable_target_tcp }}'"

  include: tcp.yml

  tags:
    - dockable
    - target
    - tcp

###################################################################################################

- name: unix

  when: "dockable_target | truncate({{ dockable_target_unix | length }}, true, '') == '{{ dockable_target_unix }}'"

  include: unix.yml

  tags:
    - dockable
    - target
    - unix

###################################################################################################

- name: verify

  command: docker version

  changed_when: false

  tags:
    - dockable
    - target

###################################################################################################
