###################################################################################################

- name: default

  when: dockable_target_is_null

  set_fact:
    dockable_target: '{{ dockable_target_default }}'

  tags:
    - dockable
    - target

###################################################################################################

- name: tcp

  when: dockable_target_is_tcp

  include: tcp.yml

  tags:
    - dockable
    - target
    - tcp

###################################################################################################

- name: unix

  when: dockable_target_is_unix

  include: unix.yml

  tags:
    - dockable
    - target
    - unix

###################################################################################################

- name: verify

  command: '{{ dockable_verify_command }}'

  changed_when: false

  tags:
    - dockable
    - target

###################################################################################################
